version: "3.1"
services:
 app:
   image: miken21/app
   ports:
    - "8082:8082"
   links:
    - mongo
   depends_on:
    - mongo
   environment:
    MONGO_URL: mongodb://mongo/restaurants
 mongo:
   image: mongo:latest
   ports:
    - "27017:27017"